Repository 42rio-projects/cub3d, pull requests merged in 2023-03, with the labels that each got.

#42 41 extension check
  Makefile
  includes/cub3d.h
  src/check_arguments.c
  src/cub3d.c
  src/error_handling.c
Labels: enhancement, new function

#45 refactor: remove norminette action
  .github/workflows/norminette.yml
Labels: refactor

#50 49 fix gtests actions
  src/check_arguments.c
  unitTests/CMakeLists.txt
  unitTests/InputTests/CMakeLists.txt
Labels: fix

#56 map validation working, open file error message with correct error
  Makefile
  includes/cub3d.h
  src/scene/scene.c
  src/scene/set_map.c
  src/scene/validate_map.c
Labels: enhancement

#61 57 adding patterns and organizing
  Makefile
  includes/cub3d.h
  includes/libft/Makefile
  includes/libft/libft.h
  maps/borderWithZero.cub
  maps/invalidColor.cub
  maps/invalidColorValue.cub
  maps/invalidDupPath.cub
  maps/invalidExtension3.cub.
  maps/invalidExtraNewLine.cub
  maps/invalidWall.cub
  maps/invalidWallBotton.cub
  maps/invalidWallLeft.cub
  maps/invalidWallRight.cub
  maps/invalidWallTop.cub
  maps/validExtension..cub
  maps/validMap000colors.cub
  maps/validMap1.cub
  maps/validMap2.cub
  maps/validMap255colors.cub
  maps/validMultipleNewLines.cub
  maps/validPdfMap.cub
  src/main/cub3d.c
  src/scene/set_info.c
  src/scene/set_map.c
  src/scene/validate_map.c
  src/utils/error_handling.c
  src/utils/free_matrix.c
  vazio.cub
Labels: refactor

#62 fix: handle overflow and fix atoi conversion
  includes/libft/ft_atoi_push.c
  includes/libft/libft.h
  src/scene/set_colors.c
Labels: fix
