Repository 42rio-projects/cub3d, pull requests merged in 2023-04, with the labels that each got.

#76 feat: clean '\n', check if has map, if is at least and has map charac…
  Makefile
  includes/cub3d.h
  src/main.c
  src/scene/scene.c
  src/utils/quit_program.c
  src/validations/validate_content.c
Labels: enhancement

#77 75 remove git workflow and unittests
  .github/workflows/gtests.yml
  .github/workflows/valgrind.yml
  Makefile
  unitTests/CMakeLists.txt
  unitTests/InputTests/CMakeLists.txt
  unitTests/InputTests/InputTests.cpp
Labels: refactor

#81 refactor: main and all values from main struct (data) is more readable
  Makefile
  includes/cub3d.h
  maps/validPdfMap.cub
  src/init/data_init.c
  src/init/elements_init.c
  src/init/set_scene.c
  src/main.c
  src/mlx/hooks.c
  src/scene/set_map.c
  src/scene/validate_map.c
  src/utils/check_extension.c
  src/utils/error_handling.c
  src/utils/free_scene.c
  src/utils/is_map_line.c
  src/utils/quit_program.c
  src/utils/throw_error.c
Labels: refactor

#84 feat: get map information, check if map is surrounded by wall
  Makefile
  includes/cub3d.h
  maps/invalidWall.cub
  maps/invalidWallBotton.cub
  maps/invalidWallLeft.cub
  maps/invalidWallRight.cub
  maps/invalidWallTop.cub
  maps/validPdfMap.cub
  src/init/data_init.c
  src/init/elements_init.c
  src/init/map_init.c
  src/scene/set_map.c
  src/scene/validate_map.c
  src/utils/free_scene.c
  src/validations/validate_grid.c
Labels: enhancement

#85 refactor: norminette and cleaned working functions
  Makefile
  includes/cub3d.h
  src/init/data_init.c
  src/init/elements_init.c
  src/main.c
  src/utils/check_extension.c
  src/utils/free_scene.c
  src/utils/is_map_line.c
  src/validations/validate_content.c
Labels: refactor

#89 feat: create player_init function to start player values
  Makefile
  include/cub3d.h
  src/init/data_init.c
  src/init/player_init.c
Labels: enhancement

#91 feat: images init and render tile
  src/init/data_init.c
  src/init/images_init.c
  src/render/render_tile.c
Labels: enhancement, new function

#95 92 player movement
  Makefile
  include/cub3d.h
  mlx_linux/mlx_init.c
  mlx_linux/mlx_xpm.c
  mlx_linux/mlx_xpm.c.ok
  src/hooks/hook.c
  src/hooks/key_pressed.c
  src/hooks/key_release.c
  src/hooks/key_released.c
  src/init/data_init.c
  src/init/image_init.c
  src/main.c
  src/render/dda.c
  src/render/draw_image.c
  src/render/render_line.c
Labels: enhancement, fix

#96 refactor: main, hooks, init, validations and utils functions, norm ok
  include/cub3d.h
  src/hooks/hook.c
  src/hooks/key_pressed.c
  src/hooks/key_released.c
  src/init/data_init.c
  src/init/elements_init.c
  src/init/image_init.c
  src/init/map_init.c
  src/init/player_init.c
  src/main.c
  src/rays/cast.c
  src/rays/raycast.c
  src/rays/rays_init.c
  src/render/draw_image.c
  src/utils/check_extension.c
  src/utils/free_scene.c
  src/utils/is_map_line.c
  src/utils/is_wall_at.c
  src/validations/validate_content.c
  src/validations/validate_grid.c
Labels: refactor

#99 98 fix some changes that were override by previus merges
  include/cub3d.h
  src/init/data_init.c
  src/render/draw_image.c
Labels: fix

#102 refactor: rays functions
  Makefile
  include/cub3d.h
  src/rays/cast.c
  src/rays/raycast.c
  src/rays/rays_init.c
  src/render/draw_image.c
  src/render/render_tile.c
Labels: refactor

#106 refactor: ft_atol.c norminette
  include/libft/ft_atol.c
Labels: refactor

#112 110 mouse hook
  Makefile
  include/cub3d.h
  src/hooks/hook.c
  src/hooks/mouse_hook.c
  src/main.c
Labels: enhancement

#114 111 doors
  include/cub3d.h
  maps/validPdfMap.cub
  src/hooks/key_pressed.c
  src/init/data_init.c
  src/init/elements_init.c
  src/rays/cast.c
  src/render/draw_image.c
  src/render/draw_vertical_line.c
  src/utils/is_map_line.c
  src/utils/is_wall_at.c
  src/validations/validate_content.c
  textures/xpm/door.xpm
Labels: enhancement

#113 109 doors interaction
  Makefile
  include/cub3d.h
  src/cast/raycast.c
  src/cast/spritecast.c
  src/init/data_init.c
  src/init/elements_init.c
  src/init/sprites_init.c
  src/render/draw_ceil_and_floor.c
  src/render/draw_ceil_wall_floor.c
  src/render/draw_image.c
  src/render/draw_sprite.c
  src/render/draw_texture.c
  src/render/set_draw_info.c
  src/utils/load_texture.c
  textures/xpm/barrel.xpm
  textures/xpm/fire.xpm
Labels: enhancement

#116 115 make dinamically sprite length and a sprite action
  Makefile
  include/cub3d.h
  src/cast/spritecast.c
  src/hooks/key_pressed.c
  src/init/data_init.c
  src/init/elements_init.c
  src/init/sprites_init.c
  src/render/draw_animation.c
  src/render/draw_image.c
  src/render/draw_sprite.c
  src/utils/free_scene.c
  src/utils/is_map_line.c
  src/utils/load_texture.c
  src/validations/validate_content.c
Labels: enhancement

#120 feat: improve mouse sensibility and fix infinity rotation loop
  bonus/include/cub3d_bonus.h
  bonus/src/hooks/key_released_bonus.c
  bonus/src/hooks/mouse_hook_bonus.c
Labels: enhancement, fix

#122 feat: doors opening and closing
  bonus/include/cub3d_bonus.h
  bonus/src/hooks/key_pressed_bonus.c
Labels: enhancement

#124 fix: pixel and mouse movement
  bonus/include/cub3d_bonus.h
  bonus/src/hooks/hook_bonus.c
  bonus/src/hooks/key_released_bonus.c
  bonus/src/hooks/mouse_hook_bonus.c
  bonus/src/render/draw_ceil_wall_floor_bonus.c
  mandatory/src/render/draw_ceil_wall_floor.c
Labels: fix
