Repository 42rio-projects/cub3d, pull requests merged in 2023-02, with the labels that each got.

#2 feat: makefile done
  Makefile
Labels: enhancement

#7 created valgrind actions
  .github/workflows/norminette.yml
  .github/workflows/valgrind.yml
  test.c
Labels: enhancement

#9 feat: done norminette.yml
  .github/workflows/norminette.yml
  src/cub3d.c
Labels: enhancement

#11 valgrind-actions done
  .github/workflows/valgrind.yml
  src/cub3d.c
Labels: enhancement

#13 Includes directory and header file created
  includes/cub3d.h
  src/cub3d.c
Labels: Setup / Plaining

#16 Adding .gitignore
  .gitignore
Labels: Setup / Plaining

#20 fix: norm running only in src & includes dir
  .github/workflows/norminette.yml
  includes/cub3d.h
  src/check_arguments.c
  src/cub3d.c
Labels: fix

#24 23 run google tests in GitHub actions
  .github/workflows/gtests.yml
  unitTests/InputTests/InputTests.cpp
Labels: enhancement

#26 feat: created window in mlx
  includes/cub3d.h
  src/cub3d.c
Labels: enhancement

#31 feat: added mac mlx & removed objects in makefile
  Makefile
  mlx/Makefile
  mlx/font.c
  mlx/font.xcf
  mlx/mlx.h
  mlx/mlx_init_loop.m
  mlx/mlx_int.h
  mlx/mlx_int_str_to_wordtab.c
  mlx/mlx_mouse.m
  mlx/mlx_new_image.m
  mlx/mlx_new_window.h
  mlx/mlx_new_window.m
  mlx/mlx_opengl.h
  mlx/mlx_opengl.m
  mlx/mlx_png.c
  mlx/mlx_png.h
  mlx/mlx_rgb.c
  mlx/mlx_shaders.c
  mlx/mlx_xpm.c
  src/cub3d.c
Labels: enhancement

#34 feat: closing win & ending program at X button
  includes/cub3d.h
  src/cub3d.c
  src/hooks.c
Labels: enhancement

#37 fix: makefile working well in macos
  Makefile
Labels: fix

#39 feat: background color set in window
  Makefile
  includes/cub3d.h
  src/create_image.c
  src/cub3d.c
  src/mlx_utils.c
Labels: enhancement

#40 29 função para desenhar um quadrado
  Makefile
  includes/cub3d.h
  src/cub3d.c
Labels: enhancement
